name: gf_web
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0
  url_launcher: ^5.4.1
  getwidget: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: icomoon
      fonts:
        - asset: lib/fonts/icomoon.ttf

  assets:
    - lib/assets/logo.png
    - lib/assets/icons/next.png
    - lib/assets/icons/buttons.png
    - lib/assets/icons/buttons.svg
    - lib/assets/icons/avatar.png
    - lib/assets/icons/badge.png
    - lib/assets/icons/card.png
    - lib/assets/icons/chips.png
    - lib/assets/icons/items.png
    - lib/assets/icons/lists.png
    - lib/assets/icons/menu.png
    - lib/assets/icons/slider.png
    - lib/assets/icons/tabs.png
    - lib/assets/icons/toast.png
    - lib/assets/icons/toggle.png
    - lib/assets/icons/typo.png
    - lib/assets/icons/images.png
    - lib/assets/icons/back.png
    - lib/assets/icons/next.png
    - lib/assets/icons/primary.svg
    - lib/assets/icons/secondary.svg
    - lib/assets/icons/success.svg
    - lib/assets/icons/warning.svg
    - lib/assets/icons/danger.svg
    - lib/assets/icons/info.svg
    - lib/assets/icons/dark.svg
    - lib/assets/icons/link.svg
    - lib/assets/icons/light.svg
    - lib/assets/icons/fb.svg
    - lib/assets/icons/twitter.svg
    - lib/assets/icons/whatsapp.svg
    - lib/assets/icons/google.svg
    - lib/assets/icons/dribble.svg
    - lib/assets/icons/youtube.svg
    - lib/assets/icons/slack.svg
    - lib/assets/icons/pinterest.svg
    - lib/assets/icons/linkedin.svg
    - lib/assets/images/image.png
    - lib/assets/images/image1.png
    - lib/assets/images/red.png
    - lib/assets/images/purple.png
    - lib/assets/images/pink.png
    - lib/assets/images/green.png
    - lib/assets/images/green1.png
    - lib/assets/images/orange.png
    - lib/assets/images/avatar1.png
    - lib/assets/images/avatar2.png
    - lib/assets/images/avatar3.png
    - lib/assets/images/avatar4.png
    - lib/assets/images/image2.png
    - lib/assets/images/img.png
    - lib/assets/images/img1.png
    - lib/assets/images/img2.png
    - lib/assets/images/card.png
    - lib/assets/images/card1.png
    - lib/assets/images/card2.png
    - lib/assets/images/card3.png
    - lib/assets/images/car.png
    - lib/assets/images/car1.png
    - lib/assets/images/car2.png
    - lib/assets/images/car3.png
    - lib/assets/images/car4.png
    - lib/assets/images/car5.png
    - lib/assets/images/a.png
    - lib/assets/images/three.png
    - lib/assets/images/two.png
    - lib/assets/images/three1.png
    - lib/assets/images/three2.png
    - lib/assets/images/three3.png
    - lib/assets/images/three4.png
    - lib/assets/images/three5.png
    - lib/assets/images/three6.png
    - lib/assets/images/three7.png
    - lib/assets/images/cir.png
    - lib/assets/gif/standard-buttons.gif
    - lib/assets/gif/pills-button.gif
    - lib/assets/gif/square-buttons.gif
    - lib/assets/gif/icon-buttons.gif
    - lib/assets/gif/social-buttons.gif
    - lib/assets/gif/cards.gif
    - lib/assets/gif/avatars.gif
    - lib/assets/gif/images.gif
    - lib/assets/gif/tiles.gif
    - lib/assets/images/Group-1170.png
    - lib/assets/gif/carousel.gif
    - lib/assets/gif/ezgif.com-resize.gif
    - lib/assets/gif/tabs.gif
    - lib/assets/gif/typography.gif
    - lib/assets/images/Artboard1.png
    - lib/assets/gif/toasts.gif
    - lib/assets/gif/toggle.gif
    - lib/assets/gif/Alerts.gif
    - lib/assets/gif/accordion.gif
    - lib/assets/gif/searchbar.gif
    - lib/assets/gif/appbar.gif
    - lib/assets/images/c1.png
    - lib/assets/images/c2.png
    - lib/assets/images/c3.png
    - lib/assets/images/c4.png
    - lib/assets/images/c5.png
    - lib/assets/images/playstore.svg
    - lib/assets/icons/playstore.svg
    - lib/assets/images/playstore3x.png
    - lib/assets/gif/loader.gif
    - lib/assets/gif/loader1.gif
    - lib/assets/gif/loaders.gif
    - lib/assets/gif/ratings.gif
    - lib/assets/gif/floating.gif
    - lib/assets/gif/Progressbar.gif
    - lib/assets/gif/Shimmer.gif
    - lib/assets/gif/radio.gif
    - lib/assets/gif/radiolist.gif
    - lib/assets/gif/Checkboxlist.gif
    - lib/assets/gif/Borders.gif
    - lib/assets/gif/Checkbox.gif
    - lib/assets/gif/bottomsheet.gif
    - lib/assets/images/gflogo.png
